# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: "Set VSIX Version Number"
description: "Sets the supplied VSIX version number in the VSIX manifest and generated code-behind file (if one exists)"
branding:
  icon: hash
  color: purple

inputs:
  version-number:
    description: "Version number to set"
    required: false
    type: string
    default: ""

  development-version:
    description: "Development version number"
    required: false
    type: string
    default: ""

  production-version:
    description: "Production version number"
    required: false
    type: string
    default: ""

  git-ref:
    description: "The repo's git ref"
    required: false
    type: string
    default: ""

  # tag-is-production:
  #   description: "A tag ref indicates production"
  #   required: false
  #   type: boolean
  #   default: false

  production-tag:
    description: "A regex expression that defines a valid production tag"
    required: false
    type: string
    default: "**"

  vsix-manifest-file:
    description: "Path to VSIX manifest file (source.extension.vsixmanifest)"
    required: true
    type: string
    default: src\vsix\source.extension.vsixmanifest

  vsix-code-file:
    description: "Path to generated code file (source.extension.vs)"
    required: false
    type: string
    default: src\vsix\source.extension.cs

runs:
  using: "composite"

  steps:
    - name: Set version in VSIX manifest file
      shell: pwsh

      run: |
        try {
          $versionNumber = ${{ inputs.version-number}}
          $development = ${{ inputs.development-version}}
          $production = ${{ inputs.production-version}}
          $gitRef = ${{ inputs.git-ref}}
          $tagIsProduction = ${{ inputs.tag-is-production }}

          if ($version == '') {
            # no version value specified, so $development, $production and $gitref are required
            if ($development == '') || ($production = '') || ($gitRef != '') {
                Write-Host -ForegroundColor Orange 'If a version is not specified, development-version, production-version and gitref are required'
            } else {  
              if ($tagIsProduction == true){
              } else{

              }
            }
          }

          Write-Host -ForegroundColor Yellow 'Version to set: "$versionNumber"'

          $filePath = "${{ inputs.vsix-manifest-file }}"
          $replacement = 'Version="$versionNumber" Language='
          $content = [string]::join([environment]::newline, (get-content $filePath))
          $regex = New-Object System.Text.RegularExpressions.Regex 'Version="([0-9\\.]+)" Language='
          $regex.Replace($content, $replacement) | Out-File $FilePath

          # display the contents of the manifest file
          Get-Content ${{ inputs.vsix-manifest-file }}
        }
        catch {
          Write-Host -ForegroundColor Red "An error occurred:"
          Write-Host -ForegroundColor Red $_.ScriptStackTrace
        }

    - name: Set version in VSIX code-behind file
      if: inputs.vsix-code-file != '' && inputs.vsix-code-file != null
      shell: pwsh

      run: |
        try {
          Write-Host -ForegroundColor Yellow "Version to set: '${{ inputs.version-number }}'"

          $filePath = "${{ inputs.vsix-code-file }}"
          $replacement = 'Version = "${{ inputs.version-number }}"'
          $content = [string]::join([environment]::newline, (get-content $filePath))
          $regex = New-Object System.Text.RegularExpressions.Regex 'Version = "([0-9\\.]+)"'
          $regex.Replace($content, $replacement) | Out-File $FilePath

          Get-Content ${{ inputs.vsix-code-file }}
        }
        catch {
          Write-Host -ForegroundColor Red "An error occurred:"
          Write-Host -ForegroundColor Red $_.ScriptStackTrace
        }
