# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: "Set VSIX Version Number"
description: "Sets the version number in the VSIX manifest and generated code-behind file (if one exists)"
author: "Yann Duran <set-vsix-version@yannduran.com>"
branding:
  icon: hash
  color: purple

inputs:
  version-number:
    description: "Version number to set"
    required: false
    default: ""

  git-ref:
    description: "The repo's git ref"
    required: false
    default: ""

  production-regex:
    description: "A regex expression that defines a valid production tag"
    required: false
    default: ""

  version-regex:
    description: "A regex expression that defines a valid version number"
    required: false
    default: ""

  development-version:
    description: "Development version number"
    required: false
    default: ""

  manifest-file-path:
    description: "Path to VSIX manifest file (source.extension.vsixmanifest)"
    required: true
    default: src/vsix/source.extension.vsixmanifest

outputs:
  version-number:
    description: "The version that was set in the VSIX manifest/code file(s)"
    value: ${{ steps.set-vsix-version.outputs.version-number }}

runs:
  using: "composite"

  steps:
    - name: Set version in VSIX manifest and file (if it exists)
      id: set-vsix-version
      shell: pwsh

      run: |
        . "& ${{ GITHUB_ACTION_PATH }}/src/Set-VsixVersion.ps1"
        Set-VsixVersion `
          -versionNumber "${{ inputs.version-number }}" `
          -gitRef "${{ inputs.git-ref }}" `
          -productionRegex "${{ inputs.production-regex }}" `
          -versionRegex "${{ inputs.version-regex }}" `
          -developmentVersion "${{ inputs.development-version }}" `
          -manifestFilePath "${{ inputs.manifest-file-path }}"
