# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: "Set VSIX Version Number"
description: "Sets the version number in the VSIX manifest and generated code-behind file (if one exists)"
branding:
  icon: hash
  color: purple

inputs:
  version-number:
    description: "Version number to set"
    required: false
    type: string
    default: ""

  development-version:
    description: "Development version number"
    required: false
    type: string
    default: ""

  production-version:
    description: "Production version number"
    required: false
    type: string
    default: ""

  production-tag:
    description: "A regex expression that defines a valid production tag"
    required: false
    type: string
    default: "**"

  git-ref:
    description: "The repo's git ref"
    required: false
    type: string
    default: ""

  manifest-file-path:
    description: "Path to VSIX manifest file (source.extension.vsixmanifest)"
    required: true
    type: string
    default: src/vsix/source.extension.vsixmanifest

  code-file-path:
    description: "Path to generated code file (source.extension.vs)"
    required: false
    type: string
    default: src/vsix/source.extension.cs

runs:
  using: "composite"

  steps:
    - name: Set version in VSIX manifest and file (if it exists)
      shell: pwsh

      run: exit 0 #|

    - name: Show results
      shell: pwsh

      run: exit 0 # |

    - name:
