name: CI Build

on:
  push:
    branches:
      - master
      - release/v**

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Set Result
      #   id: set-result

      #   uses: actions/github-script@v6
      #   with:
      #     script: return "Hello!"
      #     result-encoding: string

      # - name: Get result
      #   run: echo "${{steps.set-result.outputs.result}}"

      - name: Version number supplied
        id: version-supplied

        uses: ./
        with:
          version-number: 1.2.3
          github-ref: ""
          production-regex: ""
          development-version: ""
          manifest-file-path: ./tests/test.vsixmanifest

      - run: echo "Version is '${{ steps.version-supplied.outputs.version-number }}'"

      - name: No version number, branch
        id: branch

        uses: ./
        with:
          version-number: ""
          github-ref: "refs/heads/master"
          production-regex: "^v[0-9]+.[0-9]+.[0-9]+$"
          development-version: "1.0.0.1"
          manifest-file-path: ./tests/test.vsixmanifest

      - run: echo "Version is '${{ steps.branch.outputs.version-number }}'"

      - name: No version number, non-production tag
        id: non-production-tag

        uses: ./
        with:
          version-number: ""
          github-ref: "/refs/tags/1.2.3"
          production-regex: "^v[0-9]+.[0-9]+.[0-9]+$"
          development-version: "1.0.0.2"
          manifest-file-path: ./tests/test.vsixmanifest

      - run: echo "Version is '${{ steps.non-production-tag.outputs.development-version }}'"

      - name: No version number, production tag
        id: production-tag

        uses: ./
        with:
          version-number: ""
          github-ref: "/refs/tags/v2.3.0"
          production-regex: "^v[0-9]+.[0-9]+.[0-9]+$"
          development-version: "1.0.0.3"
          manifest-file-path: ./tests/test.vsixmanifest

      - run: echo "Version is '${{ steps.production-tag.outputs.development-version }}'"
