name: CI Build

on:
  push:
    branches:
      - master
      - release/v**

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Has version number and manifest file path
        id: version-supplied

        uses: ./
        with:
          version-number: 1.2.3
          manifest-file-path: ./tests/test.vsixmanifest

      - run: echo "Version is '${{ steps.version-supplied.outputs.version-number }}'"

      - name: Has no version number and branch ref
        id: branch

        uses: ./
        with:
          version-number: ""
          git-ref: "refs/heads/master"
          development-version: "1.0.0.1"
          manifest-file-path: ./tests/test.vsixmanifest

      - run: echo "Version is '${{ steps.branch.outputs.version-number }}'"

      - name: Has no version number and non-production tag
        id: non-production-tag

        uses: ./
        with:
          version-number: ""
          git-ref: "/refs/tags/1.2.3"
          production-regex: "^v[0-9]+.[0-9]+.[0-9]+$"
          development-version: "1.0.0.2"
          manifest-file-path: ./tests/test.vsixmanifest

      - run: echo "Version is '${{ steps.non-production-tag.outputs.development-version }}'"

      - name: Has no version number and production tag
        id: production-tag

        uses: ./
        with:
          version-number: ""
          git-ref: "/refs/tags/v2.3.0"
          production-regex: "^v[0-9]+.[0-9]+.[0-9]+$"
          development-version: "1.0.0.3"
          manifest-file-path: ./tests/test.vsixmanifest

      - run: echo "Version is '${{ steps.production-tag.outputs.development-version }}'"
