name: Test Action

on:
  push:
    branches:
      - master
      - release/v**

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Supply version number to set
        id: supply-version
        uses: ./
        with:
          version-number: "'1.2.3'"
          manifest-file-path: "'test.vsixmanifest'"
          code-file-path: "'test.cs'"
      - run: echo "Version is '${{ steps.supply-version.outputs.version-number }}'"

      # - name: development
      # - uses: yannduran/set-vsix-version@master
      #   with:
      #     development-version: "'1.2.3.4'"
      #     production-version: "'4.5.0'"
      #     production-tag: "'^v[0-9]+.[0-9]+.[0-9]+$'"
      #     git-ref: "'refs/heads/master'"
      #     manifest-file-path: "'test.vsixmanifest'"
      #     code-file-path: "'test.cs'"
