name: CI Build

on:
  push:
    branches:
      - master
      - release/v**

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Set Result
      #   id: set-result

      #   uses: actions/github-script@v6
      #   with:
      #     script: return "Hello!"
      #     result-encoding: string

      # - name: Get result
      #   run: echo "${{steps.set-result.outputs.result}}"

      - name: Version number supplied
        id: version-supplied

        uses: ./
        with:
          version-number: 1.2.3
          development-version: ""
          production-version: ""
          production-regex: ""
          github-ref: ""
          manifest-file-path: ./.github/workflows/test.vsixmanifest
          code-file-path: ./.github/workflows/test.cs

      - run: echo "Version is '${{ steps.version-supplied.outputs.version-number }}'"

      - name: No version number, missing inputs
        id: missing-data

        uses: ./
        with:
          version-number: ""
          development-version: ""
          production-version: ""
          production-regex: ""
          github-ref: ""
          manifest-file-path: ./.github/workflows/test.vsixmanifest
          code-file-path: ./.github/workflows/test.cs

      - run: echo "Version is '${{ steps.missing-data.outputs.version-number }}'"

      - name: No version number, missing deveopment version
        id: missing-development-version

        uses: ./
        with:
          version-number: ""
          development-version: ""
          production-version: "1.3.0"
          production-regex: "^v[0-9]+.[0-9]+.[0-9]+$"
          github-ref: "/refs/heads/master"
          manifest-file-path: ./.github/workflows/test.vsixmanifest
          code-file-path: ./.github/workflows/test.cs

      - run: echo "Version is '${{ steps.missing-development-version.outputs.development-version }}'"
