name: Test Action

on:
  push:
    branches:
      - master
      - release/v**

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Supply version number to set
        id: version-supplied

        if: false

        uses: yannduran/set-vsix-version@v0.2.15 #./
        with:
          version-number: 1.2.3
          development-version: ""
          production-version: ""
          production-tag: ""
          github-ref: ""
          manifest-file-path: ./.github/workflows/test.vsixmanifest
          code-file-path: ./.github/workflows/test.cs

      - run: echo "Version is '${{ steps.version-supplied.outputs.version-number }}'"

      - uses: actions/checkout@v2

      - name: Missing data
        id: missing-data
        uses: yannduran/set-vsix-version@v0.2.15 #./
        with:
          version-number: ""
          development-version: ""
          production-version: ""
          production-tag: ""
          github-ref: ""
          manifest-file-path: ./.github/workflows/test.vsixmanifest
          code-file-path: ./.github/workflows/test.cs

      - run: echo "Version is '${{ steps.missing-data.outputs.version-number }}'"
