// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CiTest_GitVersion
{
    internal sealed partial class Vsix
    {
        public const string Id = "35864e59-962b-49fc-a592-074dee03b36e";
        public const string Name = "CI Test - GitVersion";
        public const string Description = @"A project to test using GitVersion in Github Actions";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Yann Duran";
        public const string Tags = "";
    }
}
